### add user
POST http://127.0.0.1:3000/admin/userRole
Content-Type: application/json

{
  "user_id": "1",
  "role_id": "2"
}

### get_users
GET http://127.0.0.1:3000/admin/userRole
Accept: application/json


