### add role
POST http://127.0.0.1:3000/admin/role
Content-Type: application/json

{
  "name": "1角色",
  "description": "1很厉害"
}

### get_roles
GET http://127.0.0.1:3000/admin/role
Accept: application/json



### get_role_permission
GET http://127.0.0.1:3000/admin/role/2/permission
Accept: application/json
